const GLOBAL = {
    CANVAS_W: 144,
    CANVAS_H: 256,
    PLAYER_W: 18,
    PLAYER_H: 12,
    PLAYER_WINGS_ANIMATION: 50,
    PIPE_INITIAL_OFFSET: 50,
    PIPE_DISTANCE: 60,
    FLOOR_H: 56,
    LANDSCAPE_SPEED: 0.2,
    SPEED: 0.5,
    GRAVITY: 0.08,
    JUMP: -2
};